### ISSUE TITLE
basic wallet functions

### ISSUE THREAD

**Issue by changtimwu** [changtimwu/react-native-boilerplate-mobx-state-tree-typescript#3]
* A mobile wallet has to built-in some functions of a web3 provider.
## Survey
* Prelimaries
  - a web3 test page -- [done](https://github.com/changtimwu/web3test-app/)
  - use wallet address not hard code address.
  - [Current EIP 712](https://github.com/0xProject/EIPs/blob/master/EIPS/eip-signTypedData.md)
* [Cipher browser](https://www.cipherbrowser.com/)
  - [x] basic send/receive
  - [x] test `eth_sign` --> incorret.  Cipher thought this as `send`.
  - [x] test `eth_signTypedData` --> excellient! it shows every name/value pairs.
* study how to do sign proof 
  - [x] [microraiden's way](https://github.com/raiden-network/microraiden/blob/master/microraiden/webui/microraiden/src/index.ts#L884)
* figure the difference 
  - On Node: web3js -> infura(EVM)
  - On Browser: web3js -> metamask(provider) -> infura(EVM) 

## Roadmap
* pure ETH send
  - [ ] API
  - [ ] UI 
* contract execution
  - [ ] API
  - [ ]  UI
* [eth.signTypedData]((https://github.com/0xProject/EIPs/blob/master/EIPS/eip-signTypedData.md) 
)
  - [ ] API
  - [ ] UI

### explain
* API: web3 provider aka backend
* UI: web3 provider caller aka frontend

## accessory functions
* receipent address input
  - [ ] QR code
  - [ ] NFC

**Comment by changtimwu** [comment]
## RN Webview

* use: https://stackoverflow.com/questions/38963046/can-i-use-webview-inside-a-view-react-native
* javascript injection: https://medium.com/capriza-engineering/communicating-between-react-native-and-the-webview-ac14b8b8b91a
* metamask inejection: https://github.com/petejkim/metamask-mobile/tree/master/src/injections

**Comment by changtimwu** [comment]
## 3 components
* dApp
* user wallet
* EVM

## The whole problem becomes  
* How much metamask should we inject into the WebView?
* In what we injected, which part should be rewritten for good mobile experience?
* 
## Goal
* Full fledge of web3.js APIs to run any dApp or
* minimum set of web3.js to support L2 payment operations.

**Comment by changtimwu** [comment]
## select L2 payment network
* to get contract address and POA site
* network disclaimer
* show as credit card

## TOP up 
* send ETH/DAI to certain address
* always should current balance

## Make payment
* trig by user selecting a card 
* use NFC reading or QR code scanning to get amount and reciever's address
* show a dialog to confirm payment by Touch/Face ID

## payment receive
* log/record and notification is done by the POA site
* show balance proof as receipt 

## withdraw
* a screen show current off-chain balance and confirm to withdraw
* notify senders?

## consideration
* are `payment receive` and `withdraw` be done in a mobile client? maybe would be enough.

**Comment by changtimwu** [comment]
## state channel simple operator interface.  
receiver = business owner = operator
* one click deploy
* what to fill before deploy
  - receiver's address
  - select token's contract address

## public page
* an introduction who the receiver is 
* contract address
* define a JSON schema for the above for operator
* explorer?
* lost recovery

## admin page
* basic info
* on-chain and off-chain balance
* transaction log
* report
  - abnormal payment
  - 
* balance

**Comment by changtimwu** [comment]
operator code deploy
* [AWS code deploy](https://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-partners-github.html)
* [heroku and Azure](https://gist.github.com/jesperorb/86952f98ed7ea3d1fbfa54824b22eee0)

**Comment by changtimwu** [comment]
https://gist.github.com/amiller/0a569536c2b5e99b307b853cbba810f6
